# Generated by Django 5.2 on 2026-01-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workshops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('day_of_the_week', models.CharField(max_length=3)),
                ('session_no', models.IntegerField()),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('fee', models.IntegerField()),
                ('tagline', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('enrolment_no', models.IntegerField()),
                ('applied_no', models.IntegerField()),
                ('tutor_name', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=500)),
                ('ws_photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('tutor_photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_date', '-start_time'],
                'indexes': [models.Index(fields=['start_date'], name='workshops_w_start_d_d0fbf7_idx')],
            },
        ),
    ]
