# Generated by Django 5.2 on 2026-01-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workshop', models.CharField(max_length=50)),
                ('ws_type', models.CharField(max_length=20)),
                ('day_of_the_week', models.CharField(max_length=3)),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('fee', models.IntegerField()),
                ('ws_photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('tagline', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('enrolment_no', models.IntegerField()),
                ('applied_no', models.IntegerField()),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_date', '-start_time'],
            },
        ),
        migrations.DeleteModel(
            name='Workshops',
        ),
        migrations.AddIndex(
            model_name='workshop',
            index=models.Index(fields=['start_date'], name='workshops_w_start_d_e8102b_idx'),
        ),
    ]
