# Generated by Django 5.2 on 2026-01-21 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0002_workshop_delete_workshops_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='description',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='fee',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='ws_type',
        ),
        migrations.AddField(
            model_name='workshop',
            name='detail',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='workshop',
            name='experience',
            field=models.CharField(default=' ', max_length=500),
        ),
        migrations.AddField(
            model_name='workshop',
            name='quote',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='workshop',
            name='tutor_name',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='workshop',
            name='tutor_photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='day_of_the_week',
            field=models.CharField(default=' ', max_length=3),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='tagline',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='workshop',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
